# Generated by Django 2.2 on 2021-05-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1492-01-01'),
            preserve_default=False,
        ),
    ]
